---
- name: change file content
  hosts: localhost
  ignore_errors: true
  tasks:
    - name: change /tmp/file
      lineinfile:
        path: /tmp/file 
        regexp: '^line2'
        insertbefore: '^line2'
        line: 'this is test' 
        create: yes
